# ==============================================================================
# Docker Compose Manifest for Home Network Security Monitoring
#
# This file deploys a multi-container stack including:
#   - Wazuh SIEM (Indexer, Manager, Dashboard)
#   - Snort IDS
#
# Usage:
#   1. Customize environment variables below (especially for Snort).
#   2. Run `docker-compose up -d` to launch the stack.
# ==============================================================================

version: '3.8'

services:
  # --- Wazuh SIEM Stack ---
  # Based on the official Wazuh docker deployment guide.

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.3
    container_name: wazuh-indexer
    hostname: wazuh-indexer
    restart: always
    ports:
      - "9200:9200" # For communication with Wazuh Manager/Dashboard
    environment:
      - "INDEXER_NODE_NAME=node-1"
      - "INDEXER_CLUSTER_NAME=wazuh-cluster"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
    networks:
      - security-monitoring-net

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.3
    container_name: wazuh-manager
    hostname: wazuh-manager
    restart: always
    depends_on:
      - wazuh-indexer
    ports:
      # Syslog collector port for pfSense logs
      - "1514:1514/udp" 
      # Wazuh agent registration/communication
      - "1515:1515"
      - "55000:55000"
    environment:
      - "WAZUH_INDEXER_URL=http://wazuh-indexer:9200"
    volumes:
      # Mount Snort logs into the Wazuh manager to be read
      - snort-logs:/var/log/snort
      # Wazuh manager configuration and data
      - wazuh-manager-data:/var/ossec/data
      - wazuh-manager-etc:/var/ossec/etc
    networks:
      - security-monitoring-net

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.3
    container_name: wazuh-dashboard
    hostname: wazuh-dashboard
    restart: always
    depends_on:
      - wazuh-indexer
      - wazuh-manager
    ports:
      # Expose the dashboard to the host network
      - "443:5601"
    environment:
      - "DASHBOARD_USERNAME=admin" # Default user, CHANGE IN PRODUCTION
      - "DASHBOARD_PASSWORD=SecretPassword" # Default password, CHANGE IN PRODUCTION
      - "DASHBOARD_INDEXER_URL=http://wazuh-indexer:9200"
      - "DASHBOARD_MANAGER_URL=https://wazuh-manager"
    networks:
      - security-monitoring-net

  # --- Snort IDS ---

  snort:
    image: amirhpr/snort:latest
    container_name: snort-ids
    restart: always
    # Host network mode is required for Snort to sniff traffic from the host's NIC
    network_mode: "host"
    # Privileged mode is needed to allow the container to access network interfaces
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    environment:
      # --- IMPORTANT: CUSTOMIZE THESE VARIABLES ---
      # Set this to the network interface of your LAN on the Docker host machine
      - SNORT_INTERFACE=eth0
      # Your free Oinkcode from snort.org for official rule downloads
      - SNORT_OINKCODE=YOUR_OINK_CODE_HERE
      # URL for the Emerging Threats Open ruleset
      - ET_PULLED_PORK_URL=https://rules.emergingthreats.net/open/snort-2.9.0/emerging.rules.tar.gz
      # Set to "detection" (IDS mode) or "inline" (IPS mode)
      - SNORT_MODE=detection
    volumes:
      # Share the log volume with the Wazuh manager
      - snort-logs:/var/log/snort

# --- Volumes & Networks ---

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
  wazuh-manager-etc:
  snort-logs:

networks:
  security-monitoring-net:
    driver: bridge
